### ISSUE TITLE
An System.AggregateException occured in MESSAGE_REACTION_ADDED.

### ISSUE THREAD

**Issue by actisPRO** [actisPRO/SeaOfThieves-Bot#28]
Происходит при добавлении реакции пользователем на codex message

**Comment by Vanguard-Fx** [comment]
Инфа по данной ошибке: https://github.com/DSharpPlus/DSharpPlus/issues/581

**Comment by Vanguard-Fx** [comment]
Закрываю так как баг на стороне апи дискорда и DSharpPlus

**Comment by Vanguard-Fx** [comment]
Если человек (в скрытом статусе) зашёл на сервер на котором много скрытых пользователей то иногда бот их не видит, пока не напишут сообщение или тому подобное.

Решение:
Добавить канал в который они смогут написать, сообщение будет удалено и выдана роль автоматом

**Comment by Vanguard-Fx** [comment]
Причина в этом


> Другая причина могла быть в отсутствии параметра PurgeCodexRole в конфиге
