### ISSUE TITLE
2.12 - аналог принятия правил для рейда

### ISSUE THREAD

**Issue by actisPRO** [actisPRO/SeaOfThieves-Bot#34]
![image](https://user-images.githubusercontent.com/31219724/84599826-34e43880-ae75-11ea-9647-629c12cbfb52.png)

**Comment by Vanguard-Fx** [comment]
- [ ] Выдача роли по принятию правил рейда
- [ ] Выдача бана по команде !purgeFleet для модераторов и "капитанов рейда", последним максимум на день
