### ISSUE TITLE
An System.AggregateException occured in GUILD_MEMBER_ADD.

### ISSUE THREAD

**Issue by actisPRO** [actisPRO/SeaOfThieves-Bot#40]

**Comment by Vanguard-Fx** [comment]
Пользователь мог заблокировать бота при отправке сообщения приветствия

**Comment by Vanguard-Fx** [comment]
Если человек (в скрытом статусе) зашёл на сервер на котором много скрытых пользователей то иногда бот их не видит, пока не напишут сообщение или тому подобное.

Решение:
Добавить канал в который они смогут написать, сообщение будет удалено и выдана роль автоматом
